### PR TITLE
Set the nameserver to 127.0.0.11:53 for wasmedge_wasi_socket 0.5.0

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

### [Commit 7d23faf8967ab5ab9944d00f83811ee6efd544ad](https://github.com/second-state/microservice-rust-mysql/pull/18/commits/7d23faf8967ab5ab9944d00f83811ee6efd544ad)
Summary of key changes:
- Added `DNS_SERVER` environment variable with the value `127.0.0.11:53` to the `services` section of `docker-compose.yml`.

Potential problems:
- It is not clear why the nameserver is being set to `127.0.0.11:53` or what impact it may have on the application.
- The rationale for this change is missing in the pull request description, making it difficult to understand the motivation behind it.
- It would be helpful to provide more context and explanation for why this change is necessary or beneficial.
- It is always a good practice to extensively test changes that involve network configurations, especially when modifying nameservers, as it may impact the overall connectivity and DNS resolving for the application.
- It would be helpful to include any relevant test cases that demonstrate the desired behavior with this new nameserver configuration.

Note: The provided patch only includes changes to `docker-compose.yml` and does not show the complete context of the code changes.

**Comment by juntao** [comment]
This DNS_SERVER is not read by the Rust code. It is a built-in feature for WasmEdge socket? The socket library automatically uses it for DNS if it is set?

**Comment by juntao** [comment]
And also why 127.0.0.11? It is a special value defined by Docker Compose?

**Comment by hydai** [comment]
> This DNS_SERVER is not read by the Rust code. It is a built-in feature for WasmEdge socket? The socket library automatically uses it for DNS if it is set?

Please refer to https://github.com/second-state/wasmedge_wasi_socket/pull/84/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R372

The `built-in-dns` feature in wasmedge_wasi_socket will try to use `8.8.8.8:53` if the `DNS_SERVER` is not set. However, docker-compose uses `127.0.0.11:53` as the nameserver.

Since we already bumped the tokio_wasi and hyper_wasi to use the `built-in-dns`, this is the workaround for making it use the correct DNS nameserver unless we release new releases by turning off the `built-in-dns` feature.

**Comment by juntao** [comment]
Ok. We should probably turn it on only if the DNS_SERVER is set.

I will merge this now.

**Review by juntao — APPROVED** [review]

**Pull request merged**
